name: CI/CD
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build with maven
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
  
  push-to-ecr:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        run: echo "Configurando credenciais"