name: CI/CD
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build with maven
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto' 
        java-version: '17'
        cache: 'maven'
  
  push-to-ecr:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        run: echo "Configurando credenciais"