name: CI/CD
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build with maven
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
    - name: Print GITHUB_REF
      run: echo "GITHUB_REF is $GITHUB_REF"
  
  push-to-ecr:
    name: Build Image
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        run: echo "Configurando credenciais"
  
  deploy_dev:
    name: Deploy dev
    needs: [build, push-to-ecr]
    runs-on: ubuntu-latest
    steps:
      - name: Executando deploy em dev
        run: echo "Executando deploy em dev"

  deploy_prd:
    needs: [deploy_dev]
    runs-on: ubuntu-latest
    if: github.event.inputs.approve == 'true'
    steps:
      - name: Executando deploy em prd
        run: echo "Executando deploy em prd"